---
- name: Hent information fra Cisco-enheder
  hosts: cisco
  gather_facts: true
  connection: local

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: admin
    ansible_password: admin
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: admin

  tasks:
    - name: Konfigurer MOTD
      cisco.ios.ios_banner:
        banner: motd
        text: "Velkommen til CHR. Adgang kun for autoriseret personale."
      register: motd_result

    - name: Gem konfiguration med ændringer
      cisco.ios.ios_config:
        save_when: modified
      when: motd_result.changed

- name: Opret logfil på Windows-serveren
  hosts: windows_servers
  gather_facts: false
  tasks:
    - name: Opret destination directory hvis den ikke findes
      win_file:
        path: "C:\\IT"
        state: directory

    - name: Opret logfil med dato og klokkeslæt
      win_shell: |
        $border = "==============================="
        $timestamp = Get-Date -Format 'dd-MM-yyyy HH:mm:ss'
        $content = "Konfigen blev sidst ændret den $timestamp"
        $border | Out-File -FilePath "C:\\IT\\log.txt" -Append -Encoding unicode
        $content | Out-File -FilePath "C:\\IT\\log.txt" -Append -Encoding unicode
