---
- name: Ping a Linux Machine
  hosts: linux  # Replace with the hostname or IP address of your Linux machine
  gather_facts: no         # We don't need to gather facts in this example
  tasks:
    - name: Ping the Linux machine
      ping:
