---
- name: Opret logfil på Windows-serveren
  hosts: 172.16.40.10
  remote_user: administrator
  gather_facts: no
  tasks:
    - name: Opret destination directory hvis den ikke findes
      win_file:
        path: "C:\\path\\to\\destination_directory"
        state: directory
      become: yes
